spring.application.name=gymflow
spring.datasource.url=jdbc:mysql://localhost:3306/gymflow_db
spring.datasource.username=root
spring.datasource.password=vali@123
spring.security.user.name=admin
spring.security.user.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=2sK9LmP8xVq7NfR4wTy8ZaBcDeFgHiJkMnOpQrStUvWxYz123456789
jwt.expiration=86400000
usda.api.key=YOUR_API_KEY

usda.api.url=https://api.nal.usda.gov/fdc/v1/foods/search